Repository openbao/openbao, pull requests merged in 2024-09, with the labels that each got.

#504 Update to Go 1.22.6 toolchain for v2.0.1
  .github/workflows/go-dependency-submission.yml
  .github/workflows/release.yml
  .go-version
  changelog/504.txt
  go.mod
Labels: enhancement

#505 Update Docker dependency
  go.mod
  go.sum
Labels: pr/no-changelog

#506 Update release process with v2.0.1 learnings
  website/content/docs/policies/release.mdx
Labels: documentation, pr/no-changelog

#508 Add meetings to community website section
  website/content/docs/contributing/index.mdx
Labels: documentation, pr/no-changelog

#511 fix command `vault print token` to `bao print token` in curl string generated by `buildCurlString()`
  api/output_string.go
  changelog/511.txt
Labels: bug

#512 Fix aliasNameFromLoginRequest panic
  changelog/512.txt
  vault/core.go
  vault/external_tests/approle/alias_name_panic_test.go
Labels: bug

#494 Add docker-based website viewer
  website/Dockerfile
  website/Makefile
Labels: docs, documentation, pr/no-changelog

#513 Add sys/internal/inspect/request endpoint
  api/plugin_helpers.go
  changelog/513.txt
  vault/logical_system.go
  vault/logical_system_paths.go
  website/content/api-docs/system/inspect/index.mdx
  website/content/api-docs/system/inspect/request.mdx
  website/sidebarsApi.ts
Labels: enhancement

#518 Minor updates to website
  README.md
  website/content/docs/contributing/index.mdx
  website/docusaurus.config.ts
  website/package-lock.json
  website/package.json
  website/public/assets/OpenBao-Technical-Charter-Final-2024-05-08.pdf
  website/src/components/FAQSection/index.tsx
Labels: documentation, pr/no-changelog

#526 Update changelogs for Release 2.0.1
  CHANGELOG.md
  website/content/docs/release-notes/2-0-0.mdx
  website/content/docs/release-notes/2-0-1.mdx
  website/sidebars.ts
Labels: documentation, pr/no-changelog

#523 Fix kubernetes Service Registration Guide
  website/content/docs/configuration/service-registration/kubernetes.mdx
Labels: docs, pr/no-changelog

#524 Document the existing package manager for MacOS homebrew
  website/content/docs/install.mdx
Labels: docs, pr/no-changelog

#528 Update "vault-" label to "openbao-" in documentation
  website/content/docs/configuration/service-registration/kubernetes.mdx
Labels: docs, pr/no-changelog, k8s

#527 Fix k8s registration variables
  changelog/527.txt
  serviceregistration/kubernetes/service_registration.go
Labels: bug, k8s

#525 Remove Zededa from TSC
  CONTRIBUTING.md
  website/src/components/Supporters/index.tsx
Labels: docs, pr/no-changelog

#538 Add checksum verification to installation docs
  website/content/docs/install.mdx
Labels: docs, pr/no-changelog

#541 Start blog, add kickoff article
  website/content/blog/2024-09-23-kickoff.md
  website/content/blog/authors.yml
  website/docusaurus.config.ts
Labels: docs, pr/no-changelog

#442 Add transaction support to cache
  sdk/physical/cache.go
Labels: enhancement, pr/no-changelog, core/storage

#498 Add transactions to PKI
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_root.go
  changelog/498.txt
Labels: enhancement, secrets/pki

#550 Add blog post on profiles
  website/content/blog/2024-09-27-profiles.md
  website/content/blog/authors.yml
Labels: pr/no-changelog, blog

#495 Support transactions in BarrierView
  vault/audit.go
  vault/audit_broker.go
  vault/audited_headers.go
  vault/auth.go
  vault/barrier_view.go
  vault/barrier_view_test.go
  vault/core.go
  vault/core_util.go
  vault/expiration.go
  vault/expiration_util.go
  vault/logical_cubbyhole.go
  vault/login_mfa.go
  vault/mount.go
  vault/mount_test.go
  vault/plugin_catalog.go
  vault/policy_store.go
  vault/policy_store_util.go
  vault/router.go
  vault/router_test.go
  vault/token_store.go
  vault/token_store_util.go
Labels: feature, pr/no-changelog, core/storage

#558 Fix transactions and PKI interactions
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_root.go
  sdk/physical/cache.go
Labels: bug, pr/no-changelog, core/storage, secrets/pki

#554 Minor improvements to Transit CSR feature
  builtin/logical/transit/path_certificates_test.go
  changelog/536.txt
Labels: pr/no-changelog

#559 Correctly handle IPv6 for HTTP-01
  builtin/logical/pki/acme_authorizations.go
  builtin/logical/pki/acme_challenge_engine.go
  builtin/logical/pki/path_acme_order.go
  changelog/559.txt
Labels: bug, secrets/pki, needs-backport

#557 Upgrade MySQL to 9.0 and Switch InfluxDB to 1.8 for M1 Compatibility
  helper/testhelpers/mysql/mysqlhelper.go
  plugins/database/influxdb/influxdb_test.go
Labels: pr/no-changelog, macos

#289 Update dependency to sigs.k8s.io/yaml
  command/format.go
  command/format_test.go
  command/pki_health_check.go
  command/pki_list_intermediate.go
  command/pki_verify_sign.go
  go.mod
  go.sum
Labels: dependencies

#568 Add Community Roles proposal to MAINTAINERS.md
  CONTRIBUTING.md
  MAINTAINERS.md
  website/content/docs/contributing/index.mdx
Labels: docs, pr/no-changelog
