Repository openbao/openbao, pull requests merged in 2024-06, with the labels that each got.

#362 Fix go tests
  .github/workflows/build-vault-ce.yml
  .github/workflows/build.yml
  .release/release-metadata.hcl
  Makefile
  README.md
  builtin/logical/pkiext/pkiext_binary/acme_test.go
  command/agent_test.go
  command/server.go
  http/handler.go
  scripts/build.sh
  scripts/ci-helper.sh
  sdk/helper/pluginutil/run_config_test.go
Labels: pr/no-changelog

#373 Limit parallelism on goreleaser
  .github/workflows/release.yml
Labels: pr/no-changelog

#375 Fix artifact signing, use default runner
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: bug, docs, pr/no-changelog, github_actions

#372 docs(token): document the token format
  website/content/docs/concepts/tokens.mdx
Labels: docs, pr/no-changelog

#368 update website dependencies
  website/package-lock.json
  website/package.json
Labels: pr/no-changelog

#378 fix release asset parsing for download page
  website/src/components/Releases/index.tsx
Labels: pr/no-changelog

#381 Downgrade test-summary/action from 2.3 to 2.2
  .github/workflows/ci.yml
Labels: pr/no-changelog, ui
