Repository openbao/openbao, pull requests merged in 2024-11, with the labels that each got.

#677 Revoked safety documentation, minor fixes
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/path_tidy_test.go
  website/content/api-docs/secret/pki.mdx
Labels: bug, pr/no-changelog, secrets/pki

#682 fix docker-entrypoint env vars
  changelog/682.txt
  scripts/docker/docker-entrypoint.sh
Labels: bug, packaging/container

#622 Split mount tables with transactions
  changelog/622.txt
  sdk/physical/error.go
  vault/auth.go
  vault/auth_test.go
  vault/external_tests/metrics/core_metrics_int_test.go
  vault/logical_system.go
  vault/logical_system_helpers.go
  vault/logical_system_test.go
  vault/mount.go
  vault/mount_test.go
  vault/plugin_reload.go
  vault/rollback_test.go
  website/content/docs/rfcs/split-mount-tables.mdx
  website/sidebars.ts
Labels: feature, core/auth, roadmap:scalability

#691 Bump github.com/golang-jwt/jwt/v4
  go.mod
  go.sum
Labels: bug, pr/no-changelog

#695 Fix root namespace permission elevation
  changelog/695.txt
  vault/identity_store.go
  vault/identity_store_entities.go
  vault/identity_store_entities_test.go
Labels: bug, blocker

#693 Bump github.com/go-jose/go-jose/v3 to v3.0.3
  api/auth/approle/go.sum
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.sum
  api/auth/userpass/go.sum
  api/go.mod
  api/go.sum
  sdk/go.mod
  sdk/go.sum
Labels: bug, pr/no-changelog

#696 Move deadlock tests to separate file
  vault/core_test.go
  vault/deadlock_test.go
Labels: bug, pr/no-changelog

#692 Bump golang.org/x/net
  api/auth/approle/go.sum
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.sum
  api/auth/userpass/go.sum
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: bug, pr/no-changelog

#698 Adjust the JWT leeway tests to reduce time sensitivity.
  builtin/credential/jwt/path_login_test.go
Labels: pr/no-changelog

#690 Compute raft peer bootstrap challenge via HKDF
  changelog/690.txt
  vault/core.go
  vault/logical_system_raft.go
  vault/raft.go
Labels: bug, blocker

#701 Update to UBI 9.5
  Dockerfile
  changelog/701.txt
Labels: bug

#699 Bump go to v1.23.3
  .go-version
  changelog/699.txt
  go.mod
Labels: bug

#697 Clean up invalid certs tidy conditions
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/path_tidy_test.go
Labels: bug, pr/no-changelog, secrets/pki

#706 Bump go-kms-wrapping versions for release
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: dependencies, pr/no-changelog, release

#705 Bump sdk to api/v2@v2.1.0
  go.mod
  sdk/go.mod
Labels: pr/no-changelog, release

#708 Bump sdk to v2.1.0 in main go.mod
  go.mod
Labels: dependencies, pr/no-changelog, release

#707 v2.1.0-beta20241114 changelog
  CHANGELOG.md
  changelog/502.txt
  changelog/504.txt
  changelog/536.txt
  changelog/699.txt
  website/content/docs/release-notes/2-1-0.mdx
  website/sidebars.ts
Labels: docs, pr/no-changelog, release

#709 Update goreleaser config version to 2
  .goreleaser-template.yaml
  Makefile
Labels: bug, pr/no-changelog, blocker, needs-backport, release

#712 Revert to github.com/hashicorp/raft-boltdb/v2@v2.0.0-20210421194847-a7e34179d62c
  go.mod
  go.sum
Labels: bug, pr/no-changelog, blocker, release

#713 Fix goreleaser prerelease status
  .goreleaser-template.yaml
  Makefile
Labels: bug, pr/no-changelog, release

#714 Replace github.com/mholt/archiver/v3 with stdlib (#611)
  changelog/611.txt
  command/debug.go
  command/debug_test.go
  go.mod
  go.sum
Labels: bug, backport-2.0.x

#721 Fix goreleaser prerelease status (#713)
  .goreleaser-template.yaml
  Makefile
Labels: bug, backport-2.0.x, release

#704 Get current time in each JWT leeway subtest
  builtin/credential/jwt/path_login_test.go
Labels: bug, pr/no-changelog, test-only

#703 [fix][inmem - Occasional logging after test finishes #702]
  sdk/physical/testing.go
Labels: bug, pr/no-changelog, test-only

#722 Update release checklist with v2.1.0-beta20241114 info
  website/content/docs/policies/release.mdx
Labels: docs, pr/no-changelog, release

#725 Bump go version to 1.22.9 for v2.0.3 release
  .go-version
  changelog/725.txt
  go.mod
Labels: release

#726 Bump golang.org/x/net
  api/auth/approle/go.sum
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.sum
  api/auth/userpass/go.sum
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: bug, release

#728 Add v2.0.3 to CHANGELOG.md
  CHANGELOG.md
Labels: pr/no-changelog, release

#729 Release notes v2.0.3
  CHANGELOG.md
  website/content/docs/release-notes/2-0-0.mdx
  website/content/docs/release-notes/2-0-1.mdx
  website/sidebars.ts
Labels: docs, pr/no-changelog

#723 PKI: clarify usage of set-signed command
  website/content/docs/secrets/pki/quick-start-intermediate-ca.mdx
Labels: docs, pr/no-changelog

#733 Update website metadata
  website/docusaurus.config.ts
  website/public/robots.txt
  website/src/pages/index.tsx
Labels: docs, pr/no-changelog

#732 Add version to download page, prerelease warning
  website/src/pages/downloads.tsx
Labels: docs, pr/no-changelog

#740 UI: Remove Sentinel verifications in policy menu
  ui/app/components/modal-form/policy-template.js
  ui/app/helpers/all-features.js
  ui/app/routes/vault/cluster/policies/create.js
  ui/app/routes/vault/cluster/policies/index.js
  ui/app/routes/vault/cluster/policy.js
  ui/app/services/download.ts
  ui/app/services/version.js
  ui/app/templates/vault/cluster/policy/show.hbs
Labels: pr/no-changelog

#735 Remove HCP Link status in UI
  ui/app/components/link-status.js
  ui/app/components/sidebar/frame.hbs
  ui/app/models/cluster.js
  ui/app/models/node.js
  ui/app/styles/components/sidebar.scss
  ui/app/templates/components/link-status.hbs
  ui/tests/integration/components/link-status-test.js
  ui/tests/integration/components/sidebar/frame-test.js
Labels: bug, pr/no-changelog, ui

#748 Replace myvault.com with example.com in tests
  builtin/credential/cert/backend_test.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/path_resign_crls_test.go
  builtin/logical/pki/path_roles_test.go
  command/agent/cert_end_to_end_test.go
  vault/identity_store_oidc_provider_test.go
Labels: pr/no-changelog, test-only

#751 fit token to openbao format
  website/content/docs/commands/print.mdx
Labels: bug, docs, pr/no-changelog

#736 Allow listing prefixed policies
  changelog/736.txt
  vault/logical_system.go
  vault/logical_system_paths.go
  vault/policy_store.go
  website/content/api-docs/system/policies.mdx
  website/content/api-docs/system/policy.mdx
Labels: feature, core/auth

#754 Remove script for portablility
  .github/scripts/verify-commits.jq
  .github/workflows/verify-commits.yml
Labels: bug, pr/no-changelog, test-only

#760 PKI: improve error message when parsing PEM bundles
  builtin/logical/pki/path_manage_issuers.go
Labels: pr/no-changelog, secrets/pki

#761 Ensure workflow runs against correct repository
  .github/workflows/verify-commits.yml
Labels: bug, pr/no-changelog, test-only

#765 Remove usage of deprecated .Subjects() in test files
  api/client_test.go
  sdk/helper/certutil/certutil_test.go
  vault/diagnose/tls_verification.go
Labels: pr/no-changelog, test-only

#771 Bump go-kms-wrapping, openbao-template
  go.mod
  go.sum
Labels: pr/no-changelog

#772 Add changelog for v2.1.0 GA
  CHANGELOG.md
Labels: docs, pr/no-changelog, release

#773 Add v2.1.0 to changelog, release notes, blog
  CHANGELOG.md
  website/content/blog/2024-10-27-transaction-details.md
  website/content/blog/2024-11-29-release-v2-1-0.md
  website/content/docs/release-notes/2-1-0.mdx
Labels: docs, pr/no-changelog
