Repository openbao/openbao, pull requests merged in 2024-12, with the labels that each got.

#777 Add download link to v2.1.0 blog post
  website/content/blog/2024-11-29-release-v2-1-0.md
Labels: docs, pr/no-changelog

#788 Replace Vault logo with Openbao in mfa- and oidc-landing page
  ui/public/images/mfa-landing.png
  ui/public/images/oidc-landing.png
Labels: bug, pr/no-changelog, ui

#781 Introduce HandleListPage Helper for Streamlined Pagination
  builtin/logical/pki/path_tidy.go
  sdk/logical/storage.go
Labels: pr/no-changelog, secrets/pki, refactor

#790 Add test for Canonicalize
  helper/namespace/namespace_test.go
Labels: pr/no-changelog, test-only

#779 Test non-voters persist across leadership changes
  physical/raft/raft_autopilot_delegate.go
  vault/external_tests/raft/raft_autopilot_test.go
Labels: pr/no-changelog, core/storage, test-only

#784 FIX UI tests
  ui/app/styles/components/console-ui-panel.scss
  ui/app/styles/core/checkbox-and-radio.scss
  ui/package.json
  ui/scripts/start-openbao.js
  ui/tests/acceptance/access/namespaces/index-test.js
  ui/tests/acceptance/auth-list-test.js
  ui/tests/acceptance/cluster-test.js
  ui/tests/acceptance/enterprise-control-groups-test.js
  ui/tests/acceptance/enterprise-kmse-test.js
  ui/tests/acceptance/enterprise-namespaces-test.js
  ui/tests/acceptance/enterprise-oidc-namespace-test.js
  ui/tests/acceptance/managed-namespace-test.js
  ui/tests/acceptance/oidc-config/clients-assignments-test.js
  ui/tests/integration/components/mount-backend/type-form-test.js
  ui/tests/integration/components/path-filter-config-list-test.js
  ui/tests/integration/components/pki/page/pki-configuration-details-test.js
  ui/tests/integration/components/pki/page/pki-configuration-edit-test.js
  ui/tests/integration/components/pki/pki-tidy-form-test.js
  ui/tests/integration/components/shamir-modal-flow-test.js
  ui/tests/integration/components/sidebar/nav/cluster-test.js
  ui/tests/integration/helpers/changelog-url-for-test.js
  ui/tests/unit/adapters/cluster-test.js
  ui/tests/unit/mixins/cluster-route-test.js
  ui/tests/unit/services/version-test.js
  ui/tests/unit/utils/decode-config-from-jwt-test.js
  ui/yarn.lock
Labels: pr/no-changelog

#792 Add blog post about 2024 RFCs
  website/content/blog/2024-12-11-rfcs-dec-2024.md
Labels: pr/no-changelog, blog

#763 Add scan operation for recursive listing
  api/logical.go
  builtin/logical/kv/backend.go
  builtin/logical/kv/passthrough.go
  builtin/logical/kv/passthrough_test.go
  builtin/logical/kv/path_metadata.go
  changelog/763.txt
  command/commands.go
  command/kv_scan.go
  command/scan.go
  command/scan_test.go
  http/cors.go
  http/logical.go
  http/logical_test.go
  sdk/framework/openapi.go
  sdk/helper/stepwise/stepwise.go
  sdk/logical/request.go
  vault/acl.go
  vault/acl_test.go
  vault/logical_system.go
  vault/policy.go
  vault/policy_test.go
  website/content/api-docs/secret/kv/kv-v1.mdx
  website/content/api-docs/secret/kv/kv-v2.mdx
  website/content/docs/concepts/policies.mdx
  website/content/docs/rfcs/index.mdx
  website/content/docs/rfcs/scan-operation.mdx
  website/sidebars.ts
Labels: feature, core/auth, secrets/kv

#797 Fix UI Tests
  .github/workflows/ci.yml
  ui/Makefile
  ui/tests/acceptance/pki/pki-action-forms-test.js
  ui/tests/acceptance/secrets/backend/alicloud/secret-test.js
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/acceptance/secrets/backend/engines-test.js
  ui/tests/acceptance/settings-test.js
  ui/tests/acceptance/settings/auth/configure/index-test.js
  ui/tests/acceptance/settings/auth/configure/section-test.js
  ui/tests/acceptance/sidebar-nav-test.js
  ui/tests/acceptance/ssh-test.js
  ui/tests/integration/components/mount-backend-form-test.js
  ui/tests/integration/components/mount-backend/type-form-test.js
  ui/tests/integration/components/pki/pki-generate-root-test.js
  ui/tests/integration/components/sidebar/frame-test.js
  ui/tests/integration/components/sidebar/nav/access-test.js
  ui/tests/integration/components/sidebar/nav/cluster-test.js
  ui/tests/integration/components/sidebar/nav/policies-test.js
  ui/tests/integration/services/auth-test.js
  ui/tests/unit/adapters/clients-activity-test.js
  ui/tests/unit/machines/secrets-machine-test.js
  ui/tests/unit/services/permissions-test.js
Labels: pr/no-changelog, ui

#793 Update key and cert chains so TLS verification tests pass
  api/test-fixtures/keys/cert.pem
  api/test-fixtures/keys/key.pem
  api/test-fixtures/root/rootcacert.pem
  api/test-fixtures/root/rootcakey.pem
  vault/diagnose/test-fixtures/goodcertbadroot.pem
  vault/diagnose/test-fixtures/goodcertwithroot.pem
  vault/diagnose/test-fixtures/goodkey.pem
  vault/diagnose/tls_verification_test.go
Labels: pr/no-changelog, test-only

#808 remove remaining Vault enterprise code from UI
  ui/app/components/mount-backend/type-form.js
  ui/app/models/pki/config/crl.js
  ui/app/models/pki/tidy.js
  ui/app/models/secret-engine.js
  ui/app/templates/components/wizard/policies-others.hbs
  ui/app/templates/vault/cluster/error.hbs
  ui/app/templates/vault/cluster/secrets/backend/error.hbs
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/lib/core/addon/components/search-select-with-modal.js
  ui/lib/core/addon/helpers/changelog-url-for.js
  ui/lib/pki/addon/components/page/pki-configuration-details.hbs
  ui/lib/pki/addon/components/page/pki-configuration-edit.hbs
  ui/lib/pki/addon/components/page/pki-tidy-status.hbs
  ui/lib/pki/addon/components/page/pki-tidy-status.ts
  ui/mirage/handlers/hcp-link.js
  ui/mirage/handlers/index.js
  ui/tests/integration/components/pki/pki-tidy-form-test.js
  ui/tests/integration/helpers/changelog-url-for-test.js
  ui/tests/unit/models/secret-engine-test.js
  ui/types/vault/models/pki/tidy.d.ts
Labels: pr/no-changelog

#803 added warning for ui on helm chart
  website/content/docs/platform/k8s/helm/run.mdx
Labels: docs, pr/no-changelog

#807 Fix `yarn npm audit` findings for ui
  ui/lib/open-api-explorer/addon/components/swagger-ui.js
  ui/lib/open-api-explorer/package.json
  ui/package.json
  ui/yarn.lock
Labels: bug, pr/no-changelog, ui

#813 ui: change sidebar coloring to match OpenBao colors
  ui/app/components/sidebar/frame.hbs
  ui/app/components/sidebar/user-menu.hbs
  ui/app/styles/app.scss
  ui/app/styles/components/sidebar.scss
Labels: feature, pr/no-changelog, ui

#814 remove target version from PR template
  .github/pull_request_template.md
Labels: pr/no-changelog

#817 ui: ensure logo is responsive
  ui/app/styles/components/header.scss
  ui/app/styles/components/icon.scss
  ui/public/openbao.svg
Labels: bug, pr/no-changelog, ui

#827 Update hashicorp/go-plugin version in SDK
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  sdk/plugin/grpc_backend_test.go
Labels: dependencies, pr/no-changelog

#829 Allow building external plugins via Makefile
  Makefile
  scripts/build.sh
Labels: pr/no-changelog

#826 Add -dev-no-store-token to container entrypoint
  Dockerfile
  changelog/826.txt
Labels: bug, packaging/container

#830 Sync dependencies between api, sdk, and root go.mod
  .github/workflows/code-checker.yml
  Makefile
  api/auth/approle/go.mod
  api/auth/approle/go.sum
  api/auth/kubernetes/go.mod
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.mod
  api/auth/ldap/go.sum
  api/auth/userpass/go.mod
  api/auth/userpass/go.sum
  api/go.mod
  api/go.sum
  go.sum
  scripts/sync-deps.sh
  sdk/go.mod
  sdk/go.sum
Labels: dependencies, pr/no-changelog

#825 Add dependabot for go.mod, container images
  .github/dependabot.yml
Labels: dependencies, pr/no-changelog

#852 Prune dependabot to only handle main module
  .github/dependabot.yml
Labels: bug, dependencies, pr/no-changelog
