Repository openbao/openbao, pull requests merged in 2024-08, with the labels that each got.

#453 Clarify Rollback and Commit semantics
  sdk/logical/storage_transactions.go
  sdk/physical/transactions.go
Labels: docs

#456 Remove myself from TSC; clarify Dev WG members
  CONTRIBUTING.md
Labels: documentation, pr/no-changelog

#454 Begin drafting release checklist
  website/content/docs/policies/index.mdx
  website/content/docs/policies/migration.mdx
  website/content/docs/policies/release.mdx
  website/sidebars.ts
Labels: documentation

#458 Fix broken zlint test
  builtin/logical/pkiext/zlint_test.go
Labels: bug, pr/no-changelog

#461 Fix Ed25519 Pointer in PKI Existing handling
  Makefile
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/ca_util.go
  changelog/461.txt
  tools/semgrep/ci/ed25519-pointer.yml
Labels: bug

#437 Add transaction support to encrypted_key_storage
  sdk/helper/keysutil/encrypted_key_storage.go
Labels: enhancement, pr/no-changelog, core/storage

#436 Add transactions to Raft backend
  physical/raft/fsm.go
  physical/raft/raft.go
  physical/raft/transaction.go
Labels: enhancement, pr/no-changelog, core/storage

#438 Add transaction support to LogicalStorage
  sdk/logical/logical_storage.go
Labels: enhancement, pr/no-changelog, core/storage

#441 Add transaction support to StorageEncoding
  sdk/physical/encoding.go
Labels: enhancement, pr/no-changelog, core/storage

#466 Correctly split TxErrors
  physical/raft/fsm.go
  tools/semgrep/ci/splitn-1.yml
Labels: bug, pr/no-changelog, core/storage

#447 add workflow to verify maintainer commits
  .github/scripts/verify-commits.jq
  .github/workflows/verify-commits.yml
Labels: pr/no-changelog

#479 Disable UI tests
  .github/workflows/ci.yml
Labels: pr/no-changelog, ui

#443 Add in-memory transactional database
  sdk/logical/storage_inmem.go
  sdk/physical/inmem/inmem.go
Labels: enhancement, pr/no-changelog, core/storage

#491 Add container registries
  website/content/docs/auth/login-mfa/faq.mdx
  website/content/docs/install.mdx
  website/content/docs/platform/k8s/csi/installation.mdx
  website/content/docs/platform/k8s/helm/examples/injector-tls.mdx
  website/content/docs/platform/k8s/injector/installation.mdx
  website/src/pages/index.tsx
Labels: docs, documentation, pr/no-changelog

#483 Ensure modifying entries do not affect cache
  changelog/483.txt
  sdk/physical/cache.go
  sdk/physical/inmem/cache_test.go
Labels: bug, core/storage

#467 Re-add Postgres storage engine
  changelog/467.txt
  command/commands.go
  physical/postgresql/postgresql.go
  physical/postgresql/postgresql_test.go
  physical/postgresql/testing.go
  website/content/docs/configuration/storage/postgresql.mdx
  website/sidebars.ts
Labels: enhancement, core/storage

#440 Support transactions in AES-GCM Barrier
  vault/barrier.go
  vault/barrier_aes_gcm.go
  vault/barrier_aes_gcm_test.go
Labels: enhancement, pr/no-changelog, core/storage
