Repository openbao/openbao, pull requests merged in 2024-10, with the labels that each got.

#287 Update dependency to github.com/cenkalti/backoff/v4
  api/auth/approle/go.sum
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.sum
  api/auth/userpass/go.sum
  api/go.mod
  api/go.sum
  api/lifetime_watcher.go
  builtin/logical/kubernetes/CHANGELOG.md
  builtin/logical/kubernetes/integrationtest/wal_rollback_test.go
  go.mod
  go.sum
  plugins/database/cassandra/cassandra_test.go
  sdk/go.mod
  sdk/go.sum
  sdk/helper/docker/testhelpers.go
Labels: dependencies, pr/no-changelog

#567 Reflect TSC Chair elections
  CONTRIBUTING.md
Labels: docs, pr/no-changelog

#572 Add blog post on community roles
  website/content/blog/2024-10-03-maintainers.md
Labels: pr/no-changelog, blog

#580 Backport #511 to release 2.0.x
  api/output_string.go
  changelog/511.txt
Labels: backport-2.0.x

#581 Backport #512 to release 2.0.x
  changelog/512.txt
  vault/core.go
  vault/external_tests/approle/alias_name_panic_test.go
Labels: backport-2.0.x

#582 Backport #527 to release 2.0.x
  changelog/527.txt
  serviceregistration/kubernetes/service_registration.go
Labels: backport-2.0.x

#583 Backport #548 to release 2.0.x
  Dockerfile
  changelog/548.txt
  scripts/docker/Dockerfile
Labels: backport-2.0.x

#584 Backport #559 to release 2.0.x
  builtin/logical/pki/acme_authorizations.go
  builtin/logical/pki/acme_challenge_engine.go
  builtin/logical/pki/path_acme_order.go
  changelog/559.txt
Labels: backport-2.0.x

#561 Deny empty valid_principals during SSH issuance
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_config_ca_test.go
  builtin/logical/ssh/path_issue_sign.go
  builtin/logical/ssh/path_roles.go
  changelog/561.txt
  website/content/api-docs/secret/ssh.mdx
Labels: bug, secrets/ssh, needs-backport

#585 Backport #561 to release 2.0.x
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_config_ca_test.go
  builtin/logical/ssh/path_issue_sign.go
  builtin/logical/ssh/path_roles.go
  changelog/561.txt
  website/content/api-docs/secret/ssh.mdx
Labels: backport-2.0.x

#497 Add transactions to plugin GRPC layer
  sdk/plugin/grpc_backend_server.go
  sdk/plugin/grpc_storage.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend.proto
  sdk/plugin/pb/backend_grpc.pb.go
  sdk/plugin/storage_test.go
Labels: feature, pr/no-changelog, core/storage

#560 Add transactions to K/V secrets engine
  builtin/logical/kv/path_config.go
  builtin/logical/kv/path_data.go
  builtin/logical/kv/path_delete.go
  builtin/logical/kv/path_destroy.go
  builtin/logical/kv/path_metadata.go
  builtin/logical/kv/path_subkeys.go
  builtin/logical/kv/upgrade.go
  changelog/560.txt
Labels: feature, secrets/kv

#591 Fix additional api, sdk references to v2
  .github/workflows/test-go.yml
  Makefile
  README.md
Labels: bug, pr/no-changelog

#602 Add LF Edge Google Tag Manager analytics
  website/docusaurus.config.ts
Labels: docs, pr/no-changelog, blog

#292 Transactional storage - Tests & RFC
  changelog/292.txt
  physical/crosstest/cross_test.go
  physical/raft/raft_test.go
  sdk/physical/file/file_test.go
  sdk/physical/inmem/cache_test.go
  sdk/physical/inmem/inmem_test.go
  sdk/physical/testing.go
  vault/external_tests/storage/crosstest/cross_test.go
  website/content/docs/rfcs/transactions.mdx
Labels: feature, core/storage

#611 Replace github.com/mholt/archiver/v3 with stdlib
  changelog/611.txt
  command/debug.go
  command/debug_test.go
  go.mod
  go.sum
Labels: dependencies, needs-backport, backport-2.0.x

#608 Add transactional storage to PostgreSQL
  changelog/608.txt
  physical/postgresql/postgresql.go
  physical/postgresql/postgresql_test.go
  physical/postgresql/transaction.go
  sdk/physical/testing.go
  website/content/docs/rfcs/index.mdx
  website/content/docs/rfcs/transactions.mdx
  website/sidebars.ts
Labels: feature, core/storage, roadmap:safer

#610 Add mailto to security email, fix others
  README.md
  builtin/credential/jwt/README.md
  builtin/credential/kubernetes/README.md
  builtin/logical/kubernetes/README.md
  builtin/logical/kv/README.md
  builtin/logical/openldap/README.md
Labels: docs, pr/no-changelog

#574 Removed rootcerts module and refactored code accordingly
  api/auth/approle/go.sum
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.sum
  api/auth/userpass/go.sum
  api/client.go
  api/go.mod
  api/go.sum
  api/rootcerts.go
  api/ssh_agent.go
  builtin/credential/cert/backend_test.go
  changelog/574.txt
  go.mod
  sdk/go.mod
  sdk/go.sum
Labels: dependencies

#606 Add roadmap blog post
  website/content/blog/2024-10-11-roadmap.md
Labels: docs, pr/no-changelog, blog

#502 Update Go version to 1.23.2
  .go-version
  changelog/502.txt
  go.mod
  go.sum
Labels: feature, pr/no-changelog

#615 Add support & release EoL policy approved by TSC
  website/content/docs/policies/index.mdx
  website/content/docs/policies/support.mdx
  website/docusaurus.config.ts
  website/sidebars.ts
Labels: docs, pr/no-changelog

#614 Allow PostgreSQL backend to create tables
  changelog/614.txt
  physical/postgresql/postgresql.go
  physical/postgresql/postgresql_test.go
  website/content/docs/configuration/storage/postgresql.mdx
Labels: feature, core/storage

#616 Fix slug & title for roadmap
  website/content/blog/2024-10-11-roadmap.md
Labels: docs, pr/no-changelog

#520 Improve download page
  website/src/components/Releases/index.tsx
  website/src/css/custom.css
  website/src/pages/downloads.tsx
Labels: docs, pr/no-changelog

#620 Add blog post from v2.0.0 release
  website/content/blog/2024-07-25-release-v2-0-0.md
Labels: pr/no-changelog, blog

#623 Document max_transaction_size Raft parameter
  website/content/docs/configuration/storage/raft.mdx
Labels: docs, pr/no-changelog, core/storage

#625 Ensure Raft transaction complies with limits
  physical/raft/raft_test.go
  physical/raft/transaction.go
Labels: bug, pr/no-changelog, core/storage

#624 Fix cache spamming logs on transaction creation; limit cache size for transactions
  sdk/physical/cache.go
Labels: bug, pr/no-changelog, core/storage

#633 Update raft, etcd/bbolt to latest versions
  changelog/633.txt
  go.mod
  go.sum
Labels: feature, core/storage

#619 Add blog article on transactional storage
  website/content/blog/2024-10-16-transactions.md
  website/content/docs/rfcs/transactions.mdx
Labels: pr/no-changelog, blog

#636 import API v2
  website/content/docs/get-started/developer-qs.mdx
Labels: bug, docs, pr/no-changelog

#641 Exclude changelog directory from release archive
  .goreleaser-template.yaml
  changelog/641.txt
Labels: bug, needs-backport

#632 Move to faster golang-lru/v2
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  sdk/helper/keysutil/encrypted_key_storage.go
  sdk/helper/keysutil/transit_lru.go
  sdk/helper/ocsp/client.go
  sdk/helper/ocsp/ocsp_test.go
  sdk/physical/cache.go
  vault/policy_store.go
Labels: dependencies, pr/no-changelog

#650 Allow verify commits to be called externally
  .github/workflows/verify-commits.yml
Labels: pr/no-changelog, github_actions

#642 Mentees first week blog
  website/content/blog/2024-10-24-mentees-first-week.md
  website/content/blog/authors.yml
  website/public/img/mentee-blog.png
Labels: pr/no-changelog, blog

#634 Improve raft transaction application performance
  physical/raft/fsm.go
  physical/raft/raft.go
  physical/raft/transaction.go
  sdk/physical/testing.go
Labels: feature, pr/no-changelog, core/storage

#652 Add FreeBSD install instructions.mdx
  website/content/docs/install.mdx
Labels: docs, pr/no-changelog

#640 chore: Fix formatting of SSH docs markdown table
  website/content/api-docs/secret/ssh.mdx
Labels: docs, pr/no-changelog

#603 Add CodeQL security analysis tooling
  .github/workflows/codeql.yml
Labels: pr/no-changelog, github_actions

#658 Add blog detailing raft transactions
  website/content/blog/2024-10-27-transaction-details.md
Labels: pr/no-changelog, blog
