Repository openbao/openbao, pull requests merged in 2024-07, with the labels that each got.

#397 docs: recreate images and diagrams
  website/content/docs/agent-and-proxy/agent/index.mdx
  website/content/docs/agent-and-proxy/index.mdx
  website/content/docs/concepts/identity.mdx
  website/content/docs/concepts/password-policies.mdx
  website/content/docs/concepts/policies.mdx
  website/content/docs/concepts/seal.mdx
  website/content/docs/internals/architecture.mdx
  website/content/docs/internals/rotation.mdx
  website/content/docs/platform/k8s/injector-csi.mdx
  website/content/docs/what-is-openbao.mdx
  website/public/img/diagram-openbao-agent.png
  website/public/img/diagram-vault-agent.png
  website/public/img/how-openbao-works.png
  website/public/img/how-vault-works.png
  website/public/img/openbao-agent-workflow.png
  website/public/img/openbao-auth-workflow.png
  website/public/img/openbao-auto-unseal.png
  website/public/img/openbao-csi-workflow.png
  website/public/img/openbao-identity-doc-1.png
  website/public/img/openbao-identity-doc-2.png
  website/public/img/openbao-identity-doc-3.png
  website/public/img/openbao-identity-doc-4.png
  website/public/img/openbao-identity-doc-5.png
  website/public/img/openbao-key-rotate.png
  website/public/img/openbao-password-policy-chance.svg
  website/public/img/openbao-password-policy-flow.svg
  website/public/img/openbao-password-policy-performance.svg
  website/public/img/openbao-policy-workflow.png
  website/public/img/openbao-shamir-seal.png
  website/public/img/openbao-sidecar-inject-workflow.png
  website/public/img/vault-agent-workflow.png
  website/public/img/vault-auth-workflow.svg
  website/public/img/vault-auto-unseal.png
  website/public/img/vault-identity-doc-2.png
  website/public/img/vault-policy-workflow.svg
  website/public/img/vault-workflow-diagram1.png
Labels: pr/no-changelog

#410 Update Go version, changelog, modules for GA
  .go-version
  CHANGELOG.md
  Makefile
  api/auth/approle/go.sum
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.sum
  api/auth/userpass/go.sum
  api/client_test.go
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  website/content/docs/release-notes/2-0-0.mdx
Labels: pr/no-changelog

#411 Add GOOS matrix to release workflow
  .github/workflows/release.yml
  .gitignore
  .goreleaser-template.yaml
Labels: docs, pr/no-changelog, github_actions

#412 Gate Docker steps behind GOOS
  .goreleaser-template.yaml
Labels: bug, docs, pr/no-changelog

#413 Add GPG key to the website
  website/content/docs/install.mdx
  website/public/assets/openbao-gpg-pub-20240618.asc
Labels: documentation, pr/no-changelog

#414 update download page logic for new release assets
  website/src/components/Releases/index.tsx
  website/src/pages/downloads.tsx
Labels: documentation, pr/no-changelog

#418 Finish docs cleanup
  website/Makefile
  website/content/docs/agent-and-proxy/agent/process-supervisor.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/cert.mdx
  website/content/docs/agent-and-proxy/proxy/apiproxy.mdx
  website/content/docs/agent-and-proxy/proxy/index.mdx
  website/content/docs/auth/login-mfa/faq.mdx
  website/content/docs/auth/login-mfa/index.mdx
  website/content/docs/concepts/seal.mdx
  website/content/docs/internals/limits.mdx
  website/content/docs/internals/telemetry/enable-telemetry.mdx
  website/content/docs/internals/telemetry/index.mdx
  website/content/docs/internals/telemetry/metrics/storage.mdx
  website/content/docs/platform/github-actions.mdx
  website/content/docs/platform/index.mdx
  website/content/docs/platform/k8s/csi/configurations.mdx
  website/content/docs/platform/k8s/csi/examples.mdx
  website/content/docs/platform/k8s/csi/index.mdx
  website/content/docs/platform/k8s/csi/installation.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/examples/development.mdx
  website/content/docs/platform/k8s/helm/examples/external.mdx
  website/content/docs/platform/k8s/helm/examples/ha-tls.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/index.mdx
  website/content/docs/platform/k8s/helm/examples/injector-tls-cert-manager.mdx
  website/content/docs/platform/k8s/helm/examples/injector-tls.mdx
  website/content/docs/platform/k8s/helm/examples/kubernetes-auth.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-audit.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-load-balanced-ui.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/helm/terraform.mdx
  website/content/docs/platform/k8s/index.mdx
  website/content/docs/platform/k8s/injector-csi.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/platform/k8s/injector/examples.mdx
  website/content/docs/platform/k8s/injector/index.mdx
  website/content/docs/platform/k8s/injector/installation.mdx
  website/content/docs/platform/servicenow/configuration.mdx
  website/content/docs/platform/servicenow/index.mdx
  website/content/docs/platform/servicenow/installation.mdx
  website/content/docs/platform/servicenow/troubleshooting.mdx
  website/content/docs/plugins/index.mdx
  website/content/docs/plugins/plugin-architecture.mdx
  website/content/docs/plugins/plugin-development.mdx
  website/content/docs/policies/index.mdx
  website/content/docs/secrets/databases/postgresql.mdx
  website/content/docs/secrets/pki/troubleshooting-acme.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
  website/content/partials/kubernetes-supported-versions.mdx
  website/docusaurus.config.ts
  website/sidebars.ts
Labels: pr/no-changelog

#420 Add known issue about SecureBits on Ubuntu 20.04
  website/content/docs/known-issues.mdx
  website/sidebars.ts
Labels: documentation, pr/no-changelog

#424 Remove legacy Dockerfile
  scripts/cross/Dockerfile
Labels: pr/no-changelog

#430 Fix typos in Makefile
  Makefile
Labels: pr/no-changelog

#422 Remove one-shot transactional interface
  command/commands.go
  command/server.go
  helper/testhelpers/teststorage/teststorage.go
  http/plugin_test.go
  physical/raft/fsm.go
  physical/raft/raft.go
  physical/raft/raft_test.go
  sdk/physical/cache.go
  sdk/physical/encoding.go
  sdk/physical/error.go
  sdk/physical/file/file.go
  sdk/physical/inmem/inmem.go
  sdk/physical/inmem/inmem_ha.go
  sdk/physical/inmem/transactions_test.go
  sdk/physical/latency.go
  sdk/physical/testing.go
  sdk/physical/transactions.go
  vault/core_util.go
  vault/custom_response_headers_test.go
  vault/external_tests/misc/recovery_test.go
  vault/logical_system_integ_test.go
  vault/sealunwrapper.go
  vault/sealunwrapper_test.go
  vault/ui_test.go
Labels: pr/no-changelog

#423 Remove SealUnwrapper
  vault/core.go
  vault/core_util.go
  vault/sealunwrapper.go
  vault/sealunwrapper_test.go
Labels: pr/no-changelog

#428 Add missing changelog for #263
  CHANGELOG.md
  changelog/263.txt
Labels: documentation, pr/no-changelog

#433 Add new transaction interfaces to sdk/
  sdk/logical/storage_transactions.go
  sdk/physical/physical.go
  sdk/physical/transactions.go
Labels: enhancement, pr/no-changelog, core/storage

#434 Fix incorrect copyright header in test
  vault/external_tests/userpass_binary/ip_token_binding_test.go
Labels: documentation, pr/no-changelog

#435 Fix OIDC challenge_code regex in test
  builtin/credential/jwt/path_oidc_test.go
Labels: bug, pr/no-changelog
